---
title: "h9"
author: "grienne"
date: "November 14, 2018"
output: html_document
---

```{r Base}

library(xlsx)
library(dplyr)
library(ggplot2)
library(readxl)

options(scipen=999)
dat <- read_excel("C:/Users/Custom PC/Desktop/PhD/CPH_738_Olga/h9/Arit+Harvanko+EC+Survey+data.xlsx")
names(dat)



## subset to only those variables we are going to work with
d <- dat[,c(3:5, 54:61, 70:71)]
names(d) <- sub(".*\\.", "", names(d))
names(d)[1:3] <- c("age", "sex", "edu")
names(d)[12:13] <- c("VG", "PG")

d$PG.level <- as.factor(with(d,
                             ifelse(PG < 34, "1",
                             ifelse(PG >= 34 & PG < 67, "2",
                                    "3"))))
d$VG.level <- as.factor(with(d,
                             ifelse(VG < 34, "1",
                             ifelse(VG >= 34 & VG < 67, "2",
                                    "3"))))
summary(d)  

```

Question 1 

1. To explore the association between dizziness and PG/VG ratio, would you use the
ordered PG-levels or the ordered VG-levels. Why or why not?
  PG levels, the article suggested that greater PG level proportions were associated with increased nicotine concentration, which by hypothesis would create more dizziness likelihood. 

```{r Question 2}

require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)

attach(d)
detach(d)

tmp.dat <- melt(d, id.vars = c("age", "sex", "edu", "VG", "PG", "PG.level", "VG.level"),
                variable.name = "effect", value.name = "score")

##how does it know which column to use for effect?

tmp.dat <- na.omit(tmp.dat)

p = ggplot(aes(x = PG.level, y = score, fill = effect), data = tmp.dat)
p + geom_boxplot() +
    geom_point(alpha = 0.3, size = 3) +
    facet_grid(. ~ effect) +
    theme_bw()



q2_fit_1 <- polr(PG.level ~ edu + age, data = d, Hess = TRUE)


summary(q2_fit_1)
###why does PG level -> VG?
```


```{R Question 3}


ci <- confint(q2_fit_1)
exp(cbind(OR = coef(q2_fit_1), ci))

```

  
